### ISSUE TITLE
Unable to setProfile for Firefox

### ISSUE THREAD

**Issue by Shyamala-Dharman** [testproject-io/java-sdk#29]
**Summary**

I am trying to set custom profile in firefoxDriver to automate my testcase. But, its not allowing to pass the profile directly to the firefoxDriver. So, I tried passing the profile through FirefoxOptionsn and Unfortunately i am getting this error ***io.testproject.sdk.internal.exceptions.AgentConnectException at AgentClient.java:608***

I am using macBook Air and created the profile using "Applications/Firefox.app/Contents/MacOS/firefox-bin -p "  in the terminal and created custom profile ("testProfile"). 

**Steps to Reproduce:**
```
ProfilesIni profile = new ProfilesIni();
FirefoxProfile myprofile = profile.getProfile("testProfile");
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.setProfile(myprofile);
driver = new FirefoxDriver(TP_DEV_TOKEN, firefoxOptions, "Web_SDK", "SampleApp Tests");
```

**Attaching the Logs:** 
[firefoxProfileError.txt](https://github.com/testproject-io/java-sdk/files/5119566/firefoxProfileError.txt)

**Tested Versions**
Mac OS  - v10.14.6
FireFox  - v79.0 - 64bit

**Comment by mstrelex** [comment]
Hi @Shyamala-Dharman 
Thanks for letting us know.
We are working on fixing this.

**Comment by mstrelex** [comment]
Hi @Shyamala-Dharman Please use Agent 0.64.1+ where this issue is resolved.

**Comment by Shyamala-Dharman** [comment]
Hi Team, 
I have verified the firefox profile issue is **fixed** with the new release v64+.
Thankyou for the help!

**Comment by mstrelex** [comment]
Thank you @Shyamala-Dharman
