### ISSUE TITLE
Test name is not reported when driver.quit() isn't called after test execution

### ISSUE THREAD

**Issue by s-glatshtein** [testproject-io/java-sdk#69]
In the following test, the reporting is wrong:
```java
@Test
public void myTestName() {
    ChromeDriver driver = new ChromeDriver(new ChromeOptions());
    driver.navigate().to("http://www.google.com");
}
```

We expect the test name to be "myTestName", but instead it is reported as "Test".
This won't happen if we add `driver.quit()` at the end of the test.

**Comment by DavidG8168** [comment]
Before:

![image](https://user-images.githubusercontent.com/45967111/104487283-961fe600-55d5-11eb-8dd9-1358c336db2a.png)

After:

![image](https://user-images.githubusercontent.com/45967111/104487330-a33cd500-55d5-11eb-9bd8-ed640579b4c6.png)

#70
